# Generated by Django 5.0.2 on 2024-10-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='UUID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время регистрации')),
            ],
            options={
                'verbose_name': 'Мобильный пользователь',
                'verbose_name_plural': 'Мобильные пользователи',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(verbose_name='Вся информация об оплате')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания записи об оплате')),
                ('mobile_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.mobileuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата пользователя',
                'verbose_name_plural': 'Оплаты пользователя',
            },
        ),
    ]
