# Generated by Django 5.0.2 on 2024-10-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='os',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'iOs')], default=0, verbose_name='os'),
            preserve_default=False,
        ),
    ]
