# Generated by Django 5.0.2 on 2024-11-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mobileuser_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_type',
            field=models.IntegerField(choices=[(0, 'product'), (1, 'subscription')], default=0, verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='os',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'iOs'), (2, 'Other')], verbose_name='os'),
        ),
    ]
