# Generated by Django 4.0.5 on 2022-06-16 11:56

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('muz_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Музыкальное название')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нота')),
                ('order', models.IntegerField(default=1, verbose_name='Номер для сортировки')),
                ('start_lad', models.IntegerField(default=1, verbose_name='С какого лада начинается')),
                ('bare', models.BooleanField(default=False, verbose_name='Есть баре?')),
            ],
            options={
                'verbose_name': 'Аккорд',
                'verbose_name_plural': 'Аккорды',
                'ordering': ('note', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.IntegerField(choices=[(0, 'Урок'), (1, 'Разбор')], verbose_name='Вид урока')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('video', models.URLField(verbose_name='Видео')),
                ('start_lesson', models.IntegerField(blank=True, null=True, verbose_name='Подходит для урока № ')),
                ('intro', models.IntegerField(default=0, verbose_name='Длительность интро')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Кодовое название')),
                ('inscription', models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись')),
                ('image', models.ImageField(upload_to='lesson_schemes/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Бой или схема',
                'verbose_name_plural': 'Бои или схемы',
            },
        ),
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, verbose_name='Версия данных')),
                ('editedAccords', models.ManyToManyField(blank=True, to='data.accord', verbose_name='Измененные аккорды')),
                ('editedLessons', models.ManyToManyField(blank=True, to='data.lesson', verbose_name='Измененные уроки')),
            ],
            options={
                'verbose_name': 'Информация об обновлении',
                'verbose_name_plural': 'Информация об обновлении',
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='StringsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.IntegerField(default=1, verbose_name='Номер струны')),
                ('lad', models.IntegerField(default=0, help_text='-1 - не играется, 0 - открытая, 1-12 - номер лада', verbose_name='На каком ладу зажата')),
                ('number', models.IntegerField(default=0, help_text='1-указательный, 2-средний, 3-безимянный, 4-мизинец', verbose_name='Каким пальцем')),
                ('accord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lads', to='data.accord', verbose_name='Аккорд')),
            ],
            options={
                'verbose_name': 'Струна',
                'verbose_name_plural': 'Струны',
                'ordering': ('string',),
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', markdownx.models.MarkdownxField(help_text='С аккордами и переносами строк', verbose_name='Текст песни')),
                ('metronome', models.IntegerField(default=0, verbose_name='Метроном')),
                ('accords', models.ManyToManyField(blank=True, to='data.accord', verbose_name='Аккорды')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='data.lesson', verbose_name='Песня к...')),
                ('schemes', models.ManyToManyField(blank=True, to='data.scheme', verbose_name='Ритмические рисунки')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('video', models.URLField(verbose_name='Видео')),
                ('intro', models.IntegerField(default=0, verbose_name='Длительность интро')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='data.lesson', verbose_name='К уроку')),
            ],
            options={
                'verbose_name': 'Дополнение к уроку',
                'verbose_name_plural': 'Дополнения к уроку',
            },
        ),
    ]
