# Generated by Django 4.0.5 on 2022-12-03 17:24

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись')),
                ('duration', models.IntegerField(choices=[(0, '1'), (1, '1/2'), (2, '1/4'), (3, '1/8'), (4, '1/16')], verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Интерактивный ритмический рисунок',
                'verbose_name_plural': 'Интерактивные ритмические рисунки',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', markdownx.models.MarkdownxField(help_text='С аккордами и переносами строк', verbose_name='Текст песни')),
                ('metronome', models.IntegerField(default=0, verbose_name='Метроном')),
                ('accords', models.ManyToManyField(blank=True, to='data.accord', verbose_name='Аккорды')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='data.lesson', verbose_name='Песня к...')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', models.IntegerField(choices=[(0, 'down'), (1, 'up'), (2, 'x'), (3, 'pause')], verbose_name='Удар')),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='data.beat', verbose_name='Ритмический рисунок')),
            ],
            options={
                'verbose_name': 'Удар',
                'verbose_name_plural': 'Удары',
            },
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name': 'Бой или схема (рисунок)', 'verbose_name_plural': 'Бои или схемы (рисунки)'},
        ),
        migrations.DeleteModel(
            name='Sound',
        ),
        migrations.AddField(
            model_name='song',
            name='schemes',
            field=models.ManyToManyField(blank=True, to='data.scheme', verbose_name='Ритмические рисунки (изображения)'),
        ),
    ]
