# Generated by Django 4.0.5 on 2023-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_updatedsubjects_delete_updateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='beat_type',
            field=models.IntegerField(choices=[(0, 'Бой'), (1, 'Перебор')], default=0, verbose_name='Вид боя'),
        ),
        migrations.AlterField(
            model_name='updatedsubjects',
            name='edited_beats',
            field=models.ManyToManyField(blank=True, to='data.beat', verbose_name='Измененнные бои'),
        ),
    ]
