# Generated by Django 4.0.5 on 2022-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_beat_song_strike_alter_scheme_options_delete_sound_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='code',
        ),
        migrations.AddField(
            model_name='song',
            name='beats',
            field=models.ManyToManyField(blank=True, to='data.beat', verbose_name='Интерактивные ритмические рисунки'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='duration',
            field=models.IntegerField(choices=[(0, '1'), (1, '1/2'), (2, '1/4'), (3, '1/8'), (4, '1/16'), (5, '1/32')], verbose_name='Длительность'),
        ),
    ]
