# Generated by Django 4.0.5 on 2023-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_beat_beat_type_alter_updatedsubjects_edited_beats'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='image',
            field=models.ImageField(height_field='height', upload_to='lesson_schemes/', verbose_name='Изображение', width_field='width'),
        ),
        migrations.AlterField(
            model_name='strike',
            name='strike',
            field=models.CharField(choices=[('down', 'Вниз'), ('up', 'Вверх'), ('x', 'Щелчок'), ('pause', 'Пауза'), ('t', 'Тоника'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('downup', 'Вниз-вверх')], max_length=30, verbose_name='Удар'),
        ),
    ]
