# Generated by Django 4.0.5 on 2022-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_scheme_code_song_beats_alter_beat_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='code',
            field=models.CharField(blank=True, help_text='Позволяет указать, для какого именно урока этот рисунок', max_length=20, verbose_name='Кодовое название'),
        ),
    ]
