# Generated by Django 4.0.5 on 2022-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_scheme_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='code',
            field=models.CharField(blank=True, help_text='Позволяет указать, для какого именно урока этот бой', max_length=20, verbose_name='Кодовое название'),
        ),
    ]
