# Generated by Django 4.0.5 on 2022-12-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_beat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='strike',
            field=models.CharField(choices=[('down', 'down'), ('up', 'up'), ('x', 'x'), ('pause', 'pause')], max_length=30, verbose_name='Удар'),
        ),
    ]
