# Generated by Django 4.0.5 on 2022-12-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_strike_strike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accord',
            new_name='Chord',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='accords',
            new_name='chords',
        ),
        migrations.AlterField(
            model_name='strike',
            name='strike',
            field=models.CharField(choices=[('down', 'Вниз'), ('up', 'Вверх'), ('x', 'Щелчок'), ('pause', 'Пауза')], max_length=30, verbose_name='Удар'),
        ),
    ]
