# Generated by Django 4.0.5 on 2022-12-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_accord_chord_rename_accords_song_chords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='data.lesson', verbose_name='Песня к...'),
        ),
    ]
