# Generated by Django 4.0.5 on 2022-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_song_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='duration',
            field=models.IntegerField(choices=[(0, '1'), (1, '1/2'), (2, '1/4'), (3, '1/8'), (4, '1/16'), (5, '1/32')], default=2, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.IntegerField(choices=[(0, 'Урок'), (1, 'Разбор')], default=0, verbose_name='Вид урока'),
        ),
    ]
